#!/usr/bin/env bash
#read the names in the text file using shell

input="./file.txt"
input_template="./template.txt"

while IFS= read -r line; do
     while IFS= read -r lines; do
	echo "$lines >> $lines.txt
     done < "$input_template"
     sed -1 -e "s/Recipients_Name/$line/" $line.txt
done < "$input"	
